### ISSUE TITLE
How can l  process my own datasets by using this script?

### ISSUE THREAD

**Issue by shentu95** [cmla/f16-video-set#1]
l am reproducing this paper and l want to use my own datasets.

If I have many videos  in a folder called videos,how can I process these videos so that they can input neural network for training?

**Comment by pariasm** [comment]
The purpose of this code is to generate the training set that we used in [this paper](https://arxiv.org/abs/1811.12758). It downloads videos from Youtube, and extract from them short clips of 16 frames. These frames are downscaled to have 540 rows. Before downscaling an anti-aliasing filter is applied (the filter width is aliased to avoid introducing a bias in the dataset). All the work is done by the script called `url-to-burst.sh`, which takes two inputs: the video URL and the output folder name. The extracted 16 frames clips are stored as png files in folders:
```output-folder/clip-number```

For training our networks we have written a simple data loader specific for data arranged in that folder structure. For example [this one](https://github.com/axeldavy/vnlnet/blob/master/dataset.py).

If I understand correctly, you already have videos. You would need to modify `url-to-burst.sh` then, by making it process a local video instead of downloading from an URL.

**Comment by shentu95** [comment]
OK.I will modify that script.

When l implemented this script,I came across this mistake. 
 Can you give me a specific example to implement this script which is called url-to-burst.sh?Thanks.

l tried this command but it didn't work and here is the error.
command:`./url-to-bursts.sh https://www.youtube.com/watch?v=zCEXYEMpB9w data/antelope/zCEXYEMpB9w output-folder`

error:`[youtube] zCEXYEMpB9w: Downloading webpage
[youtube] zCEXYEMpB9w: Downloading video info webpage
jq: error: Could not open file data/antelope/zCEXYEMpB9w/full-video.info.json: No such file or directory
jq: error: Could not open file data/antelope/zCEXYEMpB9w/full-video.info.json: No such file or directory
jq: error: Could not open file data/antelope/zCEXYEMpB9w/full-video.info.json: No such file or directory
jq: error: Could not open file data/antelope/zCEXYEMpB9w/full-video.info.json: No such file or directory
./url-to-bursts.sh: line 32: * 540 / : syntax error: operand expected (error token is "* 540 / ")
./url-to-bursts.sh: line 60: [: 30: unary operator expected
rm: cannot remove 'data/antelope/zCEXYEMpB9w/full-video': No such file or directory
`

**Comment by pariasm** [comment]
Some of the videos have been removed from Youtube. If you find problems you should check if the video url is still valid.

Try this command:
`./url-to-bursts.sh https://www.youtube.com/watch?v=hmqCBgZe0V8 data/antelope/hmqCBgZe0V8`
